import { Kanit } from "next/font/google";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



const kanit = Kanit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-kanit",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${kanit.variable}`}
      >
        {children}
      </body>
    </html>
  );
}



/*
export default function RootLayout({children,}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={kanit.variable}>
      <body>{children}</body>
    </html>
  );
}
*/